// frontend/src/pages/public/auth/LoginView.tsx
import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../../../context/AuthContext";

export default function LoginView() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);
    try {
      await login({ email, password });
      navigate("/");
    } catch {
      setError("登入失敗，請確認帳號密碼是否正確。");
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center px-6 py-16">
      <div className="flex w-full max-w-[708px] overflow-hidden rounded-md border border-line bg-[#0c0d0e]">
        <div className="relative hidden w-[260px] shrink-0 bg-[#16181b] sm:block">
          <img src="/assets/auth-login.png" alt="" className="absolute inset-0 h-full w-full object-cover" />
          <div
            className="absolute inset-0"
            style={{ background: "linear-gradient(180deg, rgba(12,13,14,0) 40%, rgba(12,13,14,.9) 100%)" }}
          />
          <div className="absolute bottom-6 left-6 font-display text-[22px] leading-[1.1] font-black tracking-tight">
            WELCOME
            <br />
            BACK.
          </div>
        </div>

        <div className="flex-1 box-border p-11">
          <Link to="/" className="flex items-center gap-2.5">
            <img src="/assets/logo-mark.png" alt="" className="h-[30px] w-[30px] rounded-[5px] object-cover" />
            <span className="font-display text-lg font-black tracking-tight">
              R<span className="mx-px" />FITNESS
            </span>
          </Link>
          <h1 className="mt-9 font-display text-[34px] font-extrabold tracking-tight">登入</h1>
          <p className="mt-2.5 text-sm font-light text-[#8a857f]">
            還沒有帳號？
            <Link to="/signup" className="text-brand-500 hover:text-brand-400">
              立即註冊
            </Link>
          </p>

          <form onSubmit={handleSubmit} className="mt-8 flex flex-col gap-5">
            <label className="block">
              <span className="font-mono text-[11px] tracking-wider text-[#8a857f]">EMAIL</span>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="you@example.com"
                className="mt-2.5 w-full rounded-[4px] border border-[#2a2d33] bg-surface px-4 py-[15px] text-body outline-none focus:border-brand-500"
                required
              />
            </label>
            <label className="block">
              <span className="font-mono text-[11px] tracking-wider text-[#8a857f]">密碼</span>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
                className="mt-2.5 w-full rounded-[4px] border border-[#2a2d33] bg-surface px-4 py-[15px] text-body outline-none focus:border-brand-500"
                required
              />
            </label>
            {error && <p className="text-sm text-rose-400">{error}</p>}
            <button
              type="submit"
              className="mt-2 w-full rounded-[4px] bg-brand-500 py-4 text-[15px] font-bold text-ink hover:bg-brand-400"
            >
              登入
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

// frontend/src/pages/public/auth/LoginView.vue
<template>
  <div class="flex min-h-screen bg-primary-900">
    <div class="flex w-full md:w-1/2 flex-col justify-center px-8 py-12">
      <div class="mx-auto w-full max-w-md space-y-6">
        <h6 class="text-4xl font-black text-primary-0 text-center">登入</h6>
        <p class="text-xl text-primary-300 text-center">請出入您的帳號和密碼</p>
        <form @submit.prevent="login" class="space-y-4">
          <div class="flex flex-col gap-2">
            <label for="email" class="text-lg font-medium text-primary-300"
              >電子郵件 <span class="text-secondary-800">*</span></label
            >
            <input
              id="email"
              type="email"
              v-model="user.email"
              class="px-4 py-2 bg-primary-800 border border-primary-600 text-primary-0 rounded-lg focus:outline-none focus:border-secondary-800"
            />
          </div>

          <div class="flex flex-col gap-2">
            <label for="password" class="text-lg font-medium text-primary-300"
              >密碼 <span class="text-secondary-800">*</span></label
            >
            <input
              id="password"
              type="password"
              v-model="user.password"
              class="px-4 py-2 bg-primary-800 border border-primary-600 text-primary-0 rounded-lg focus:outline-none focus:border-secondary-800"
            />
          </div>

          <button
            type="submit"
            class="w-full bg-secondary-800 text-primary-900 text-lg py-2 mt-2 rounded-lg font-medium hover:opacity-90 transition-opacity"
          >
            登入
          </button>

          <p class="text-center text-sm text-primary-400">
            還沒有帳號?
            <router-link
              to="/signup"
              class="text-secondary-800 font-medium hover:underline"
              >立即註冊</router-link
            >
          </p>
        </form>
      </div>
    </div>

    <div class="hidden md:flex md:w-1/2 md:py-16 md:pr-8">
      <img
        src="https://images.unsplash.com/photo-1593079831268-3381b0db4a77?q=80&w=1200&auto=format&fit=crop"
        alt="健身房環境"
        class="w-full object-cover rounded-lg"
      />
    </div>
  </div>
</template>

<script setup>
import { ref, getCurrentInstance } from "vue";
import { useRouter } from "vue-router";
import { postLogin } from "../../../api/index.js";
import swalHandler from "../../../utils/swalHandler.js";
import { setKeyFromCookie } from "../../../utils/cookie.js";
import { jwtDecode } from "jwt-decode";
import { useUserStore } from "../../../stores/user.js";

const { proxy } = getCurrentInstance();
const router = useRouter();
const { setCurrentUser } = useUserStore();

const user = ref({
  email: "",
  password: "",
});

async function login() {
  try {
    const { data } = await postLogin(user.value);

    const { role, exp } = jwtDecode(data.token);

    setKeyFromCookie("token", data.token, exp);

    setCurrentUser({
      name: data.user.name,
      role,
    });

    // 根據角色導向不同頁面
    if (role === "COACH") {
      router.push("/coach/profile");
    } else if (role === "USER") {
      router.push("/user/dashboard");
    }
  } catch (error) {
    let msg = error.message;

    if (Object.hasOwn(error.response, "data")) {
      const { status, message } = error.response.data;
      msg = message;

      if (status === "failed") {
        swalHandler(proxy.$swal, message);
        return;
      }
    }

    throw new Error(`[getCoachCourseList] error : ${msg}`);
  }
}
</script>
